// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kihgsifqcauhvpybhydm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpaGdzaWZxY2F1aHZweWJoeWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTI2NTYsImV4cCI6MjA2NjE2ODY1Nn0.4C2J4Qn639sENlKnTgHtgflPY7oNSwUwDrooHX16nVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);